### ISSUE TITLE
Getting `Failed to open the input "/tmp/speaker.wav" (No such file or directory)`

### ISSUE THREAD

**Issue by Hades32** [lucataco/cog-xtts-v2#1]
@lucataco  When running it on https://replicate.com/lucataco/xtts-v2 either with wav or mp3 files

**Comment by lucataco** [comment]
User error.
Example of Replicate model working with wav file:
https://replicate.com/p/olfmvmbb6zjp3du4rsspk3ggsq
And mp3 file:
https://replicate.com/p/gnlu2zbbq4hgdubx5kkzn6lbzy
