### ISSUE TITLE
KeyError when using language=zh-cn (Chinese)

### ISSUE THREAD

**Issue by Pwntus** [lucataco/cog-xtts-v2#3]
I'm getting a KeyError whenever I choose `zh-cn` as `language` input value:
```
File "/root/.pyenv/versions/3.11.6/lib/python3.11/site-packages/TTS/tts/layers/xtts/tokenizer.py", line 180, in expand_abbreviations_multilingual
for regex, replacement in _abbreviations[lang]:
~~~~~~~~~~~~~~^^^^^^
KeyError: 'zh-cn'
```

Looking in the source I can only find a `zh` key, but Cog won't let me try that on Replicate due to input validation schema:
https://github.com/coqui-ai/TTS/blob/dev/TTS/tts/layers/xtts/tokenizer.py#L174

**Comment by lucataco** [comment]
Thanks for the find! 
XTTS-v1 used "zh-cn" and looks like XTTS-v2 uses "zh". 
I also added support for "hu" and "ko"

**Comment by shulin2008cn** [comment]
Can Vietnamese be supported
