### ISSUE TITLE
What is the ideal duration of the speaker file?

### ISSUE THREAD

**Issue by zeke** [lucataco/cog-xtts-v2#5]
I'm running https://replicate.com/lucataco/xtts-v2 and wondering how long of a speech sample I should send it for the `speaker` input... 10 seconds? 1 minute? 10 minutes? Wondering if the performance improves with more audio, or if there are diminishing returns.

@lucataco

**Comment by zeke** [comment]
Here are my tests:

- 30s: https://replicate.com/p/rwcnbjzbenu6ioplfesjp4z72y
- 1min: https://replicate.com/p/kfrdvmrb4jolvlz4gxa63pwrvq
- 3min: https://replicate.com/p/akilvcrbb3m6hrm3wlibkewdte
- 13min: https://replicate.com/p/kdybluzbollk4mybrbhbmhojui

Conclusion: 🤷🏼 13 minutes only sounds marginally better than 30 seconds.

**Comment by lucataco** [comment]
Based on the HF docs it seems that the base model expects [6 seconds of audio](https://huggingface.co/coqui/XTTS-v2)
However, it would be super helpful to know how long of an audio clip you need for a good [fine-tune](https://tts.readthedocs.io/en/latest/models/xtts.html#training)
